import type { Metadata } from "next";
import "./globals.css";
import "equilibrium.js/dist/css/equilibrium.css";

export const metadata: Metadata = {
  title: "Equilibrium.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
